### ISSUE TITLE
 Cannot open include file: 'ofxDarkKnightMidi.hpp'?

### ISSUE THREAD

**Issue by AdmiralPotato** [luiscript/ofxDarkKnight#1]
It looks like this file isn't even in the git repo?

`https://github.com/luiscript/ofxDarkKnight/tree/master/src`

**Comment by luiscript** [comment]
This could be fixed by adding [ofxDarkKnightMidi](https://github.com/luiscript/ofxDarkKnightMidi) and [ofxMidi](https://github.com/danomatika/ofxMidi). But if you don't need a MIDI controller please pull the last commit, this will fix the problem.

Thanks for reporting the issue.
