### ISSUE TITLE
error in OF10.1 MacOS

### ISSUE THREAD

**Issue by moebiussurfing** [luiscript/ofxDarkKnight#2]
hey, I am getting this error:
```
/Users/u/Documents/of_v0.10.1_osx_release/addons/ofxDarkKnight/libs/DarkKnightMapping/src/ofxDarkKnightMapping.cpp:92:47: Too many arguments to function call, expected 3, have 4
 mesh_->setup(2,2,fboInput->getWidth(),fboInput->getHeight());
```

I added all the addons forks you listed, created /src folder (not present addons.make...) into the /example, and created the project with PG...

I am just interesed in some minimal expression of the patching system... Also curious to check it out.

**Comment by moebiussurfing** [comment]
i tried also your ofxMeshWarp but I am getting more errors..

**Comment by luiscript** [comment]
Hey! thanks for reporting me this. I wasn't using the last version of ofxMeshWarp, it was an easy fix. Please pull my last commit and use the original ofxMeshWarp addon from the autor, not my fork.

The easiest way to update this is by going to `ofxDarkKnight/libs/DarkKnightMapping` then `git pull`.

Let me know if this fix your problem, If you have any other issue I'll be happy to help.

**Comment by moebiussurfing** [comment]
hey, thanks. 
there's no .git/ folder in ofxDarkKnight/libs/DarkKnightMapping. I just made git submodule update --init --recursive into ofxDarkKnight/
Now fails here:
/Users/usr/Documents/of_v0.10.1_osx_release/addons/ofxDarkKnight/src/ofxDarkKnight.hpp:45:10: 'DarkKnightFboRecorder.hpp' file not found

**Comment by luiscript** [comment]
Even if there's no .git folder "it should work" because it is a submodule, git should know where to download the repo, but what you did it's correct.

Sorry about this new issue, When I fixed the last one I pushed some code that I don't supposed to, now you have two options, just comment the line that it's including  `DarkKnightFboRecorder.hpp` in `ofxDarkKnight.hpp` or pull the last commit again and update submodules, in this case you will need to include [ofxFboRecorder](https://github.com/vanderlin/ofxFboRecorder) because I added the new [DarkKnightVideoRecorder](https://github.com/luiscript/DarkKnightVideoRecorder) module.

I hope that next time it works, don't forget to add "High resolution capable - YES" in your `openFrameworks-Info.plist`.

**Comment by moebiussurfing** [comment]
ok. thanks
```
/Users/u/Documents/of_v0.10.1_osx_release/addons/ofxHapPlayer/libs/ofxHap/src/AudioDecoder.cpp:35:1: Use of undeclared identifier 'ofxHap'
/Users/u/Documents/of_v0.10.1_osx_release/addons/ofxHapPlayer/libs/ofxHap/src/AudioDecoder.cpp:35:42: Unknown type name 'AudioParameters'
/Users/u/Documents/of_v0.10.1_osx_release/addons/ofxHapPlayer/libs/ofxHap/src/AudioDecoder.cpp:86:1: Use of undeclared identifier 'ofxHap'
/Users/u/Documents/of_v0.10.1_osx_release/addons/ofxHapPlayer/libs/ofxHap/src/AudioDecoder.cpp:104:5: Use of undeclared identifier 'ofxHap'
/Users/u/Documents/of_v0.10.1_osx_release/addons/ofxHapPlayer/libs/ofxHap/src/AudioDecoder.cpp:149:5: Use of undeclared identifier 'ofxHap'
/Users/u/Documents/of_v0.10.1_osx_release/addons/ofxHapPlayer/libs/ofxHap/src/AudioDecoder.cpp:165:5: Use of undeclared identifier 'ofxHap'
/Users/u/Documents/of_v0.10.1_osx_release/addons/ofxHapPlayer/libs/ofxHap/src/AudioDecoder.cpp:203:6: Use of undeclared identifier 'ofxHap'
```
now I am getting this. 
I had ofxHapPlayer already, but copied again. Also your DarkKnightHap..

**Comment by moebiussurfing** [comment]
also if I make a git pull inside a lib folder in terminal I get:
```
:DarkKnightVideoRecorder u$ git pull
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.
    git pull <remote> <branch>
```
So I make git pull inside /ofxDarkKnight like I said, but I have no answer..
```
:ofxDarkKnight u$ pwd
/Documents/of_v0.10.1_osx_release/addons/ofxDarkKnight
:ofxDarkKnight u$ git submodule update --init --recursive
:ofxDarkKnight u$ 
```

I use Github desktop...

**Comment by luiscript** [comment]
ofxHapPlayer & ofxAudioAnalyzer had a conflict with a file named AudioDecoder.h, both uses the same filename with different functionality. By just renaming this file in one of the addons should take that problem away. If you don't want to do it manually you can download a [fork of ofxHapPlayer](https://github.com/luiscript/ofxHapPlayer) I did with this changes. ofxHapPlayer is working with the libavformat branch with [some issues](https://github.com/bangnoise/ofxHapPlayer/issues/46) so take care about that too.

Once again, thanks for helping me find this issues, I hope in the end it will worth it.

**Comment by moebiussurfing** [comment]
ok, thanks! it worked. 

(last step was to remove the ofxDatGui I added to the PG, and it was already there)

One more thing if you don't mind, I can't scroll to SKETCH POOL module maybe because of my low res monitor, 1440x900. I changed the window size in main.cpp but do not "resize" the gui position... 
![Screen Shot 2019-05-30 at 00 30 06](https://user-images.githubusercontent.com/2106149/58596042-e3b9d480-8272-11e9-8713-ea13e8db00ec.png)

**Comment by luiscript** [comment]
It looks like you're just missing this:

> don't forget to add "High resolution capable" to "YES" in your openFrameworks-Info.plist file.

Did you change that?

**Comment by moebiussurfing** [comment]
Yes, I did this. But I will check again

**Comment by moebiussurfing** [comment]
![Screen Shot 2019-05-30 at 12 33 13](https://user-images.githubusercontent.com/2106149/58627648-08946300-82d8-11e9-8e96-b76728bd56c1.png)

**Comment by moebiussurfing** [comment]
searching on the drop down list (not writing by hand, so there is some upper cases..), clean and run. and it's the same (release and debug schemes)
![Screen Shot 2019-05-30 at 12 41 46](https://user-images.githubusercontent.com/2106149/58627828-73459e80-82d8-11e9-907d-9d6d3ebcdf39.png)

**Comment by luiscript** [comment]
I did a small change to fix the module list position, can you try again? If the list does not appear exactly at the middle of the screen, I need to do something else to support different screen resolutions. I haven't test it on screens resolutions lower than a retina display.

As a workaround you can change line 54 of `ofxDarkKnight.cpp` and fix the list position maybe to (0,0):

`componentsList->setPosition(0,0);`

with that you will be able to see all the modules (I hope so). The mapping grid module won't work if you scroll your interface, (I'm working to fix that too). Everything else should work fine.

Let me know if this works for you, I hope you have fun with the addon.

**Comment by moebiussurfing** [comment]
cool, thanks. now it's working fine. it looks really good!

I'll look around, I would like to use a minimal version like I asked you in instagram, i'll try what you said there. 

Could be nice to have a basic wire patching (or custom new module) between ofParameters to add ofxDarkKnight into some "generalistic ofApp" when you don't need all the modules. (Or to use only the "allways required ones" like audio analysis / midi clock sync / midi/OSC control... patched to any other internal ofApp parameters. It can save lot of code time compared to adding ofxMidi/ofxOsc..etc addons on every new project and linking the parameters to send/receive them).

cheers

![Screen Shot 2019-05-30 at 21 35 25](https://user-images.githubusercontent.com/2106149/58660304-6c914880-8325-11e9-9ef9-7b83afb58bf4.png)
![Screen Shot 2019-05-30 at 21 50 44](https://user-images.githubusercontent.com/2106149/58660306-6c914880-8325-11e9-872f-c3addaee526e.png)

**Comment by luiscript** [comment]
Nice! I'm glad is working! I will try to decouple the wire system from all the modules as an independent addon. But now that you already did all the setup, you can start creating your own sketch and that's when the fun starts.

I'll love to see some evidence if you create with it... Feel free to ping me.

Salud.
