### ISSUE TITLE
errors when compiling the example in OF v0.11.1 (ubuntu 20.04)

### ISSUE THREAD

**Issue by wozhub** [luiscript/ofxDarkKnight#4]
Hi there! I'm getting some errors when trying to compile the example at OF v0.11.1 (ubuntu 20.04)

`
/home/dvzroot/OF/addons/ofxDarkKnight/libs/modules/DKConfig.hpp: In member function ‘float* DKConfig::getWiresTension()’:
/home/dvzroot/OF/addons/ofxDarkKnight/libs/modules/DKConfig.hpp:147:5: error: no return statement in function returning non-void [-Werror=return-type]
`

I moved the code to a src folder and used projectGenerator. Here's the addon.make content:
`
ofxDarkKnight
ofxMidi
ofxPostProcessing
ofxOsc
ofxAutoReloadedShader
ofxAbletonLink
ofxLua
ofxThreadedFileDialog
ofxMeshWarp
ofxFboRecorder
ofxHapPlayer
`

(I installed the addons forks the README points to whenever possible)

[make.stderr.txt](https://github.com/luiscript/ofxDarkKnight/files/7799869/make.stderr.txt)
[make.stdout.txt](https://github.com/luiscript/ofxDarkKnight/files/7799870/make.stdout.txt)

Let me know if there's anything else I can do to help you out.

**Comment by luiscript** [comment]
Hello, thanks for your effort on trying to make this work on Linux, I currently don't have support for it, but it looks like the error you described it's an easy fix: please look for the `DKConfig.hpp` file and you can comment this lines or add the return statement: 
```c++     
float * getWiresTension()
{
   return &wiresTension
} 
```
That should fix that error, but I'm not sure if everything else will work.

I will keep this issue open in case that you face another problem. 

Thanks for your help.

Luis

**Comment by wozhub** [comment]
Hello Luis! Thank you for developing such a great addon!

After adding the return statement I'm getting the following error:

`
/home/dvzroot/OF/addons/ofxDarkKnight/src/DKWireConnection.cpp: In member function ‘ofColor DKWireConnection::getWireConnectionColor()’:
/home/dvzroot/OF/addons/ofxDarkKnight/src/DKWireConnection.cpp:148:1: error: control reaches end of non-void function [-Werror=return-type]
  148 | }
      | ^
`

Here's the method that fails:
```c
ofColor DKWireConnection::getWireConnectionColor()
{
        if (connectionType == DKConnectionType::DK_FBO
        || connectionType == DKConnectionType::DK_MULTI_FBO) return ofColor(180, 180, 0);
        if (connectionType == DKConnectionType::DK_SLIDER) return ofColor(255, 255, 255);
        if (connectionType == DKConnectionType::DK_LIGHT) return ofColor(0, 180, 180);
        if (connectionType == DKConnectionType::DK_CHAIN) return ofColor(226, 88, 33);
}
```

I added a return statement at the bottom, just to get past this error... And now things got interesting:

```
/usr/include/c++/9/functional: In substitution of ‘template<class _Functor, class ... _Bound_args> template<class _Fn, class _CallArgs, class ... _BArgs> using _Res_type_impl = typename std::result_of<_Fn&(std::_Bind<_Functor(_Bound_args ...)>::_Mu_type<_BArgs, _CallArgs>&& ...)>::type [with _Fn = float; _CallArgs = _CallArgs; _BArgs = {}; _Functor = float; _Bound_args = {}]’:
/usr/include/c++/9/functional:447:8:   required from ‘struct std::_Bind<float()>’
/home/dvzroot/OF/addons/ofxDarkKnight/libs/DKLua/src/DKLua.cpp:204:32:   required from here
/usr/include/c++/9/functional:443:8: error: no type named ‘type’ in ‘class std::result_of<float&()>’
  443 |  using _Res_type_impl
      |        ^~~~~~~~~~~~~~
/usr/include/c++/9/functional: In substitution of ‘template<class _Functor, class ... _Bound_args> template<class _Fn, class _CallArgs, class ... _BArgs> using _Res_type_impl = typename std::result_of<_Fn&(std::_Bind<_Functor(_Bound_args ...)>::_Mu_type<_BArgs, _CallArgs>&& ...)>::type [with _Fn = float; _CallArgs = std::tuple<_Tps ...>; _BArgs = {}; _Functor = float; _Bound_args = {}]’:
/usr/include/c++/9/functional:447:8:   required by substitution of ‘template<class _Functor, class ... _Bound_args> template<class _CallArgs> using _Res_type = std::_Bind<_Functor(_Bound_args ...)>::_Res_type_impl<_Functor, _CallArgs, _Bound_args ...> [with _CallArgs = std::tuple<_Tps ...>; _Functor = float; _Bound_args = {}]’
/usr/include/c++/9/functional:480:2:   required from ‘struct std::_Bind<float()>’
/home/dvzroot/OF/addons/ofxDarkKnight/libs/DKLua/src/DKLua.cpp:204:32:   required from here
/usr/include/c++/9/functional:443:8: error: no type named ‘type’ in ‘class std::result_of<float&()>’
/home/dvzroot/OF/addons/ofxDarkKnight/libs/DKLua/src/DKLua.cpp: In member function ‘void DKLua::addParameter(ofxDatGuiButtonEvent)’:
/home/dvzroot/OF/addons/ofxDarkKnight/libs/DKLua/src/DKLua.cpp:215:30: error: no matching function for call to ‘bind(int&)’
  215 |             bind(*newIntParam);
      |                              ^
In file included from /home/dvzroot/OF/libs/openFrameworks/utils/ofConstants.h:284,
                 from /home/dvzroot/OF/libs/openFrameworks/ofMain.h:6,
                 from /home/dvzroot/OF/addons/ofxDarkKnight/src/DKModule.hpp:26,
                 from /home/dvzroot/OF/addons/ofxDarkKnight/libs/DKLua/src/DKLua.h:26,
                 from /home/dvzroot/OF/addons/ofxDarkKnight/libs/DKLua/src/DKLua.cpp:23:
/usr/include/c++/9/functional:808:5: note: candidate: ‘template<class _Func, class ... _BoundArgs> typename std::_Bind_helper<std::__is_socketlike<_Func>::value, _Func, _BoundArgs ...>::type std::bind(_Func&&, _BoundArgs&& ...)’
  808 |     bind(_Func&& __f, _BoundArgs&&... __args)
      |     ^~~~
/usr/include/c++/9/functional:808:5: note:   template argument deduction/substitution failed:
/usr/include/c++/9/functional: In substitution of ‘template<class _Func, class ... _BoundArgs> typename std::_Bind_helper<std::__is_socketlike<_Func>::value, _Func, _BoundArgs ...>::type std::bind(_Func&&, _BoundArgs&& ...) [with _Func = int&; _BoundArgs = {}]’:
/home/dvzroot/OF/addons/ofxDarkKnight/libs/DKLua/src/DKLua.cpp:215:30:   required from here
/usr/include/c++/9/functional:808:5: error: no type named ‘type’ in ‘struct std::_Bind_helper<true, int&>’
/usr/include/c++/9/functional:832:5: note: candidate: ‘template<class _Result, class _Func, class ... _BoundArgs> typename std::_Bindres_helper<_Result, _Func, _BoundArgs>::type std::bind(_Func&&, _BoundArgs&& ...)’
  832 |     bind(_Func&& __f, _BoundArgs&&... __args)
      |     ^~~~
/usr/include/c++/9/functional:832:5: note:   template argument deduction/substitution failed:
/home/dvzroot/OF/addons/ofxDarkKnight/libs/DKLua/src/DKLua.cpp:215:30: note:   couldn’t deduce template parameter ‘_Result’
  215 |             bind(*newIntParam);
      |  
```

**Comment by luiscript** [comment]
The ofxLua addon is the main reason I'm not giving support for Linux, it requires a fix in the addon itself to be compatible with my addon that I can't code right now. So I believe that the easiest way to solve this problem it to get rid of all the code that involves ofxLua in the openframeworks project and DKLua in the ofxDarkKnight addon too. That could be a tricky change... Sorry about this, I hope you can solve it. If you have any questions on how to remove all the Lua code let me know.

**Comment by wozhub** [comment]
Thanks for your time! I saw Linux wasn't explicitly supported but thought it might be easier to fix... Nevermind.

I'm a little bit rusty with C++, so let me install a VM with Windows first and test and play there with ofxDarkKnight. If everything goes well I'll ask for some directions on how to remove Lua code. You can close the issue if it makes sense to you. Thank you again for your support and for building such an amazing plugin!

**Comment by luiscript** [comment]
No problem, thanks to you for trying to fix it.
